WebApplicationDemo/Models/StudentGroup.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplicationDemo.Models
{
    public class StudentGroup
    {
        public int Id { get; set; }
        [DisplayName("Студентська група")]
        public string Name { get; set; } = string.Empty;
        public IEnumerable<Student>? Students { get; set; }
    }
}

WebApplicationDemo/Controllers/StudentGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplicationDemo.Data;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class StudentGroupsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public StudentGroupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/StudentGroups
        [HttpGet]
        public async Task<ActionResult<IEnumerable<StudentGroup>>> GetStudentGroup()
        {
          if (_context.StudentGroup == null)
          {
              return NotFound();
          }
            return await _context.StudentGroup.ToListAsync();
        }

        // GET: api/StudentGroups/5
        [HttpGet("{id}")]
        public async Task<ActionResult<StudentGroup>> GetStudentGroup(int id)
        {
          if (_context.StudentGroup == null)
          {
              return NotFound();
          }
            var studentGroup = await _context.StudentGroup.FindAsync(id);

            if (studentGroup == null)
            {
                return NotFound();
            }

            return studentGroup;
        }

        // PUT: api/StudentGroups/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutStudentGroup(int id, StudentGroup studentGroup)
        {
            if (id != studentGroup.Id)
            {
                return BadRequest();
            }

            _context.Entry(studentGroup).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentGroupExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/StudentGroups
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<StudentGroup>> PostStudentGroup(StudentGroup studentGroup)
        {
          if (_context.StudentGroup == null)
          {
              return Problem("Entity set 'ApplicationDbContext.StudentGroup'  is null.");
          }
            _context.StudentGroup.Add(studentGroup);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetStudentGroup", new { id = studentGroup.Id }, studentGroup);
        }

        // DELETE: api/StudentGroups/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteStudentGroup(int id)
        {
            if (_context.StudentGroup == null)
            {
                return NotFound();
            }
            var studentGroup = await _context.StudentGroup.FindAsync(id);
            if (studentGroup == null)
            {
                return NotFound();
            }

            _context.StudentGroup.Remove(studentGroup);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool StudentGroupExists(int id)
        {
            return (_context.StudentGroup?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplicationDemo/Pages/StudentGroups/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplicationDemo.Data;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Pages.StudentGroups
{
    public class CreateModel : PageModel
    {
        private readonly WebApplicationDemo.Data.ApplicationDbContext _context;

        public CreateModel(WebApplicationDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public StudentGroup StudentGroup { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.StudentGroup == null || StudentGroup == null)
            {
                return Page();
            }

            _context.StudentGroup.Add(StudentGroup);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApplicationDemo/Pages/StudentGroups/CreateStudent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplicationDemo.Data;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Pages.StudentGroups
{
    public class CreateStudentModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public CreateStudentModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet(int studentGroupId)
        {
            Student = new Student { StudentGroupId = studentGroupId };
            return Page();
        }

        [BindProperty]
        public Student Student { get; set; } = default!;



        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || _context.Students == null || Student == null)
            {
                return Page();
            }

            _context.Students.Add(Student);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Details");
        }
    }
}

WebApplicationDemo/Pages/StudentGroups/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplicationDemo.Data;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Pages.StudentGroups
{
    public class DeleteModel : PageModel
    {
        private readonly WebApplicationDemo.Data.ApplicationDbContext _context;

        public DeleteModel(WebApplicationDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public StudentGroup StudentGroup { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.StudentGroup == null)
            {
                return NotFound();
            }

            var studentgroup = await _context.StudentGroup.FirstOrDefaultAsync(m => m.Id == id);

            if (studentgroup == null)
            {
                return NotFound();
            }
            else 
            {
                StudentGroup = studentgroup;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.StudentGroup == null)
            {
                return NotFound();
            }
            var studentgroup = await _context.StudentGroup.FindAsync(id);

            if (studentgroup != null)
            {
                StudentGroup = studentgroup;
                _context.StudentGroup.Remove(StudentGroup);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplicationDemo/Pages/StudentGroups/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplicationDemo.Data;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Pages.StudentGroups
{
    public class DetailsModel : PageModel
    {
        private readonly WebApplicationDemo.Data.ApplicationDbContext _context;

        public DetailsModel(WebApplicationDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public StudentGroup StudentGroup { get; set; } = default!;
      public IList<Student> Student { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.StudentGroup == null)
            {
                return NotFound();
            }

            var studentgroup = await _context.StudentGroup.FirstOrDefaultAsync(m => m.Id == id);
            if (studentgroup == null)
            {
                return NotFound();
            }
            else 
            {
                StudentGroup = studentgroup;
            }

            Student = _context.Students.Where(s=>s.StudentGroupId==StudentGroup.Id).ToList();

            return Page();
        }
    }
}

WebApplicationDemo/Pages/StudentGroups/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationDemo.Data;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Pages.StudentGroups
{
    public class EditModel : PageModel
    {
        private readonly WebApplicationDemo.Data.ApplicationDbContext _context;

        public EditModel(WebApplicationDemo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public StudentGroup StudentGroup { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.StudentGroup == null)
            {
                return NotFound();
            }

            var studentgroup =  await _context.StudentGroup.FirstOrDefaultAsync(m => m.Id == id);
            if (studentgroup == null)
            {
                return NotFound();
            }
            StudentGroup = studentgroup;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(StudentGroup).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentGroupExists(StudentGroup.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool StudentGroupExists(int id)
        {
          return (_context.StudentGroup?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplicationDemo/Pages/StudentGroups/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplicationDemo.Data;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Pages.StudentGroups
{
    public class IndexModel : PageModel
    {
        private readonly WebApplicationDemo.Data.ApplicationDbContext _context;
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(WebApplicationDemo.Data.ApplicationDbContext context, ILogger<IndexModel> logger)
        {
            _context = context;
            _logger = logger;
        }

        public IList<StudentGroup> StudentGroup { get;set; } = default!;

        [BindProperty]
        public string searchName { get; set; } = "Contains";

        [BindProperty]
        public string searchDirection { get; set; }

        public async Task OnGetAsync()
        {
            if (_context.StudentGroup != null)
            {
                var result = _context.StudentGroup.AsQueryable();
                if (!string.IsNullOrEmpty(searchName))
                {
                    switch (searchDirection)
                    {
                        case "Contains":
                            result = result.Where(s => s.Name.Contains(searchName));
                            break;
                        case "StartWith":
                            result = result.Where(s => s.Name.StartsWith(searchName));
                            break;
                        case "EndWith":
                            result = result.Where(s => s.Name.EndsWith(searchName));
                            break;

                    }
                }
                StudentGroup = await result.ToListAsync();
            }
        }
   
        public async Task OnPostFilterAsync()
        {
            _logger.LogInformation("The set filter searchDirestion={0} searchString={1}", searchDirection, searchName);
            //_logger.LogInformation($"The set filter searchDirestion={searchDirection} searchString={searchName}");
            {
                var result = _context.StudentGroup.AsQueryable();
                if (!string.IsNullOrEmpty(searchName))
                {
                    switch (searchDirection)
                    {
                        case "Contains":
                            result = result.Where(s => s.Name.Contains(searchName));
                            break;
                        case "StartWith":
                            result = result.Where(s => s.Name.StartsWith(searchName));
                            break;
                        case "EndWith":
                            result = result.Where(s => s.Name.EndsWith(searchName));
                            break;

                    }
                }
                StudentGroup = await result.ToListAsync();
            }

        }


    }
}

WebApplicationDemo/Pages/StudentGroups/StudentEdit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationDemo.Data;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Pages.StudentGroups
{
    public class StudentEditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public StudentEditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Student Student { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            Student = student;
            ViewData["StudentGroupId"] = new SelectList(_context.StudentGroup, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Student).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentExists(Student.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool StudentExists(int id)
        {
            return (_context.Students?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplicationDemo/Pages/StudentGroups/Create.cshtml
@page
@model WebApplicationDemo.Pages.StudentGroups.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StudentGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentGroup.Name" class="control-label"></label>
                <input asp-for="StudentGroup.Name" class="form-control" />
                <span asp-validation-for="StudentGroup.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationDemo/Pages/StudentGroups/CreateStudent.cshtml
@page
@model CreateStudentModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input hidden asp-for="Student.StudentGroupId" />
            <div class="form-group">
                <label asp-for="Student.Name" class="control-label"></label>
                <input asp-for="Student.Name" class="form-control" />
                <span asp-validation-for="Student.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Surname" class="control-label"></label>
                <input asp-for="Student.Surname" class="form-control" />
                <span asp-validation-for="Student.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Email" class="control-label"></label>
                <input asp-for="Student.Email" class="form-control" />
                <span asp-validation-for="Student.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Birthday" class="control-label"></label>
                <input asp-for="Student.Birthday" class="form-control" />
                <span asp-validation-for="Student.Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Details" asp-route-StudentGroupId="@Model.Student.StudentGroupId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationDemo/Pages/StudentGroups/Delete.cshtml
@page
@model WebApplicationDemo.Pages.StudentGroups.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentGroup</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StudentGroup.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StudentGroup.Name)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="StudentGroup.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

WebApplicationDemo/Pages/StudentGroups/Details.cshtml
@page
@model WebApplicationDemo.Pages.StudentGroups.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StudentGroup</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StudentGroup.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StudentGroup.Name)
        </dd>
    </dl>
</div>

<p>
    <a asp-page="./CreateStudent" asp-route-studentGroupId="@Model.StudentGroup.Id">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Student[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student[0].Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student[0].Birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student[0].StudentGroup)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Student)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Birthday)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<div>
    <a asp-page="./Edit" asp-route-id="@Model.StudentGroup?.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

WebApplicationDemo/Pages/StudentGroups/Edit.cshtml
@page
@model WebApplicationDemo.Pages.StudentGroups.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StudentGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StudentGroup.Id" />
            <div class="form-group">
                <label asp-for="StudentGroup.Name" class="control-label"></label>
                <input asp-for="StudentGroup.Name" class="form-control" />
                <span asp-validation-for="StudentGroup.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationDemo/Pages/StudentGroups/Index.cshtml
@page
@model WebApplicationDemo.Pages.StudentGroups.IndexModel

@{
    ViewData["Title"] = "Index";
    var sl = new List<SelectListItem>();
    sl.Add(new SelectListItem { Text = "StartWith" });
    sl.Add(new SelectListItem { Text = "EndWith" });
    sl.Add(new SelectListItem { Text = "Contains" });

}

<div class="row justify-content-between">
    <div class="col-12 col-md-2">
        <a asp-page="Create" class="btn btn-primary"><span class="bi bi-alarm"></span></a>
    </div>
    <div class="col-12 col-md-auto d-flex justify-content-end">
        <form asp-page-handler="Filter">    
       
            @Html.DropDownList("searchDirection",sl,"Напрямок пошуку:")
                     Назва: @Html.TextBox("SearchName")
                     <input type="submit" value="Фільтрувати" class="btn btn-primary"/>
        </form>
    
    </div>
</div>

<table class="table table-color">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StudentGroup[0].Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.StudentGroup) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplicationDemo/Pages/StudentGroups/StudentEdit.cshtml
@page
@model StudentEditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Student.Id" />
            <input hidden asp-for="Student.StudentGroupId" />
            <div class="form-group">
                <label asp-for="Student.Name" class="control-label"></label>
                <input asp-for="Student.Name" class="form-control" />
                <span asp-validation-for="Student.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Surname" class="control-label"></label>
                <input asp-for="Student.Surname" class="form-control" />
                <span asp-validation-for="Student.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Email" class="control-label"></label>
                <input asp-for="Student.Email" class="form-control" />
                <span asp-validation-for="Student.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Birthday" class="control-label"></label>
                <input asp-for="Student.Birthday" class="form-control" />
                <span asp-validation-for="Student.Birthday" class="text-danger"></span>
            </div>
             <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}