WebApplicationMVCDemo/Models/StudentGroup.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplicationMVCDemo.Models
{
    public class StudentGroup
    {
        public int Id { get; set; }
        [DisplayName("Студентська група")]
        public string Name { get; set; } = string.Empty;
        public IEnumerable<Student>? Students { get; set; }
    }
}

WebApplicationMVCDemo/Controllers/StudentGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVCDemo.Data;
using WebApplicationMVCDemo.Models;

namespace WebApplicationMVCDemo.Controllers
{
    public class StudentGroupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentGroupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: StudentGroups
        public async Task<IActionResult> Index(string searchName,string searchDirection)
        {
            if (_context.StudentGroup == null)
                return Problem("Entity set 'ApplicationDbContext.StudentGroup'  is null.");
            var result = _context.StudentGroup.AsQueryable();
            if (!string.IsNullOrEmpty(searchName))
            {
                switch (searchDirection)
                {
                    case "Contains":
                        result = result.Where(s => s.Name.Contains(searchName));
                        break;
                    case "StartWith":
                        result = result.Where(s => s.Name.StartsWith(searchName));
                        break;
                    case "EndWith":
                        result = result.Where(s => s.Name.EndsWith(searchName));
                        break;

                }
            }
            return  View(await result.ToListAsync());
        }

        // GET: StudentGroups/Details/5
        public async Task<IActionResult> Details(int? id,string searchName,string searchSurname,bool caseInsensetiv,SearchDirection direction)
        {
            if (id == null || _context.StudentGroup == null)
            {
                return NotFound();
            }

            var studentGroup = await _context.StudentGroup.Include(s=>s.Students)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (studentGroup == null)
            {
                return NotFound();
            }

            var students = _context.Students.Where(s => s.StudentGroupId == studentGroup.Id);
            if (!string.IsNullOrEmpty(searchName))
            {
                students.Where(s=>s.Name.Contains(searchName));
            }
            if (!string.IsNullOrEmpty(searchSurname))
            {
                students.Where(s => s.Name.Contains(searchSurname));
            }

            return View(studentGroup);
        }

        // GET: StudentGroups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StudentGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] StudentGroup studentGroup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(studentGroup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(studentGroup);
        }

        // GET: StudentGroups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StudentGroup == null)
            {
                return NotFound();
            }

            var studentGroup = await _context.StudentGroup.FindAsync(id);
            if (studentGroup == null)
            {
                return NotFound();
            }
            return View(studentGroup);
        }

        // POST: StudentGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] StudentGroup studentGroup)
        {
            if (id != studentGroup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studentGroup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentGroupExists(studentGroup.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(studentGroup);
        }

        // GET: StudentGroups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StudentGroup == null)
            {
                return NotFound();
            }

            var studentGroup = await _context.StudentGroup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (studentGroup == null)
            {
                return NotFound();
            }

            return View(studentGroup);
        }

        // POST: StudentGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StudentGroup == null)
            {
                return Problem("Entity set 'ApplicationDbContext.StudentGroup'  is null.");
            }
            var studentGroup = await _context.StudentGroup.FindAsync(id);
            if (studentGroup != null)
            {
                _context.StudentGroup.Remove(studentGroup);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentGroupExists(int id)
        {
          return (_context.StudentGroup?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplicationMVCDemo/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVCDemo.Data;
using WebApplicationMVCDemo.Models;

namespace WebApplicationMVCDemo.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Students.Include(s => s.StudentGroup);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.StudentGroup)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }


        public async Task<IActionResult> VerifyStudentName(string name)
        {
            if (name.Length < 15) return Json(false);
            return Json(true);
        }
        // GET: Students/Create
        public IActionResult Create(int StudentGroupId)
        {
            
            return View(new Student {StudentGroupId=StudentGroupId });
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Email,Birthday,StudentGroupId")] Student student)
        {
            if (student.Name.Length < 3)
            {
                ModelState.AddModelError(nameof(student.Name), "Імя має бути не меньше 3-х символів");
            }
            if (student.Name.Length > 15)
            {
                ModelState.AddModelError(nameof(student.Name), "Імя має бути не быльше 15-ти символів");
            }
            if (student.Name.Length > 0 && char.IsLower(student.Name[0]))
            {
                ModelState.AddModelError(nameof(student.Name), "Імя має має починатись з великої букви");
            }


            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            ViewData["StudentGroupId"] = new SelectList(_context.StudentGroup, "Id", "Id", student.StudentGroupId);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Email,Birthday,StudentGroupId")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StudentGroupId"] = new SelectList(_context.StudentGroup, "Id", "Id", student.StudentGroupId);
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.StudentGroup)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Students'  is null.");
            }
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
          return (_context.Students?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplicationMVCDemo/Views/StudentGroups/Create.cshtml
@model WebApplicationMVCDemo.Models.StudentGroup

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StudentGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationMVCDemo/Views/StudentGroups/Delete.cshtml
@model WebApplicationMVCDemo.Models.StudentGroup

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplicationMVCDemo/Views/StudentGroups/Details.cshtml
@model WebApplicationMVCDemo.Models.StudentGroup

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StudentGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<p>
    <a asp-controller="Students" asp-action="Create" asp-route-StudentGroupId="@Model.Id">Create New</a>
</p>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Students.First().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Students.First().Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model =>model.Students.First().Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Students.First().Birthday)
            </th>
              <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Students)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Birthday)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplicationMVCDemo/Views/StudentGroups/Edit.cshtml
@model WebApplicationMVCDemo.Models.StudentGroup

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StudentGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationMVCDemo/Views/StudentGroups/Index.cshtml
@model IEnumerable<WebApplicationMVCDemo.Models.StudentGroup>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@using (Html.BeginForm("Index","StudentGroups",FormMethod.Get))
{

    <p>

       @{
            var sl = new List<SelectListItem>();
            sl.Add(new SelectListItem { Text = "StartWith" });
            sl.Add(new SelectListItem { Text = "EndWith" });
            sl.Add(new SelectListItem { Text = "Contains" });

        }
        Напрямок пошуку: @Html.DropDownList("searchDirection",sl))
        Назва: @Html.TextBox("SearchName") <input type="submit" value="Фільтрувати"/></p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>